"""Tests for runtime, shim, and product scaffold skill surfaces."""

from __future__ import annotations

import unittest
from pathlib import Path


WORKSPACE_ROOT = Path(__file__).resolve().parents[2]


class SkillSurfaceTests(unittest.TestCase):
    def test_continue_and_agentjob_runtime_surfaces_are_removed(self) -> None:
        for relative in [
            ".agents/skills/continue",
            ".codex/skills/continue",
            ".agents/skills/agentjob-task-packet-author",
            ".codex/skills/agentjob-task-packet-author",
            "Sys4AI/skills/core/continue",
            "Sys4AI/skills/core/agentjob-task-packet-author",
        ]:
            self.assertFalse((WORKSPACE_ROOT / relative).exists(), relative)

    def test_active_runtime_source_first_memory_skill_exists(self) -> None:
        text = _read(".agents/skills/source-first-memory/SKILL.md")

        self.assertIn("name: source-first-memory", text)
        self.assertIn("Memory lookup finds likely sources. It does not decide truth or permission.", text)
        self.assertIn("Inspect the canonical source path or registry row", text)

    def test_codex_shims_point_to_agents_runtime_skills(self) -> None:
        memory_text = _read(".codex/skills/source-first-memory/SKILL.md")

        self.assertIn(".agents/skills/source-first-memory/SKILL.md", memory_text)
        self.assertIn("compatibility shim", memory_text)

    def test_init_exists_in_runtime_shim_and_product_scaffold(self) -> None:
        runtime = _read(".agents/skills/init/SKILL.md")
        shim = _read(".codex/skills/init/SKILL.md")
        product = _read("Sys4AI/skills/core/init/SKILL.md")

        for invocation in ["/init", "/init greenfield", "/init brownfield", "/init temp_prd"]:
            self.assertIn(invocation, runtime)
            self.assertIn(invocation, product)

        self.assertIn(".agents/skills/init/SKILL.md", shim)
        self.assertIn("compatibility shim", shim.lower())

    def test_init_brownfield_first_pass_is_read_only(self) -> None:
        runtime = _read(".agents/skills/init/SKILL.md")
        product = _read("Sys4AI/skills/core/init/SKILL.md")

        self.assertIn("For brownfield work, keep the first pass read-only.", runtime)
        self.assertIn("Inspect only. Do not write files during the first pass.", runtime)
        self.assertIn("For brownfield systems, perform the first pass in read-only inspection mode.", product)

    def test_init_prd_creation_is_explicitly_gated(self) -> None:
        prompt = "Discovery is complete. Should I create a Product Requirements Document with `/conversation-to-prd` using the current discovery evidence?"

        for relative in [
            ".agents/skills/init/SKILL.md",
            "Sys4AI/skills/core/init/SKILL.md",
            "Sys4AI/docs/skill_integration_policy.md",
        ]:
            text = _read(relative)
            self.assertIn(prompt, text, relative)
            self.assertIn("explicit approval", text, relative)

    def test_init_candidate_requirements_remain_candidate_labeled(self) -> None:
        for relative in [
            ".agents/skills/init/SKILL.md",
            "Sys4AI/skills/core/init/SKILL.md",
            "Sys4AI/templates/system_definition/current-state-baseline-template.md",
        ]:
            text = _read(relative)
            self.assertIn("REQ-CAND-*", text, relative)
            self.assertIn("NFR-CAND-*", text, relative)

    def test_product_scaffold_init_is_generic(self) -> None:
        product_paths = [
            "Sys4AI/skills/core/init/SKILL.md",
            "Sys4AI/skills/core/init/README.md",
            "Sys4AI/skills/core/init/AGENTS.md",
            "Sys4AI/skills/core/init/examples/portable-example.md",
        ]

        for relative in product_paths:
            text = _read(relative)
            self.assertNotIn("Sys4AI-dev", text, relative)
            self.assertNotIn("Canonical runtime path", text, relative)

        product_skill = _read("Sys4AI/skills/core/init/SKILL.md")
        self.assertIn("target system generated by Sys4AI", product_skill)
        self.assertIn("not itself active development-system authority", product_skill)

    def test_product_scaffold_skills_are_generic(self) -> None:
        for relative in [
            "Sys4AI/skills/core/source-first-memory/SKILL.md",
            "Sys4AI/skills/core/source-first-memory/README.md",
            "Sys4AI/skills/core/source-first-memory/AGENTS.md",
            "Sys4AI/skills/core/source-first-memory/examples/portable-example.md",
        ]:
            text = _read(relative)
            self.assertNotIn("Codex", text, relative)
            self.assertRegex(text, r"target[ -]system", relative)

    def test_context_45_temp_prd_is_threshold_only(self) -> None:
        rule = "Do not create, overwrite, or refresh `temp_prd.md` after each question when context is still safe."
        failure = "metrics are unavailable"
        archive_preflight = "On normal invocation without `temp_prd`, run the archive preflight"
        resume_bypass = "When invoked with `temp_prd`, skip the archive preflight"
        archive_path = "archived_temp_prd/temp_prd_date_yyyy-mm-dd-hh-mm-ss.md"
        archive_helper = "archive_temp_prd.py"

        for skill in [
            "decision-grilling-context-45",
            "domain-grilling-with-docs-context-45",
            "system-definition-interview-context-45",
        ]:
            for relative in [
                f".agents/skills/{skill}/SKILL.md",
                f"Sys4AI/skills/core/{skill}/SKILL.md",
            ]:
                text = _read(relative)
                normalized = " ".join(text.split())
                self.assertIn(rule, normalized, relative)
                self.assertRegex(text, r"context left is (at most 55 percent|55 percent or lower|`<= 55%`)", relative)
                self.assertIn(failure, text, relative)
                self.assertIn(archive_preflight, text, relative)
                self.assertIn(resume_bypass, text, relative)
                self.assertIn(archive_path, text, relative)
                self.assertIn(archive_helper, text, relative)

        policy = _read("Sys4AI/docs/skill_integration_policy.md")
        normalized_policy = " ".join(policy.split())
        self.assertIn(rule, normalized_policy)
        self.assertIn("not the normal per-question state file", policy)
        self.assertIn(archive_path, policy)
        self.assertIn(archive_helper, policy)

    def test_context_45_prd_handoff_is_user_gated(self) -> None:
        prompt = "Questioning is complete. Should I create a PRD with `/conversation-to-prd` using the current discussion and `temp_prd.md` if it exists?"
        no_auto = "Do not create the PRD automatically"
        before_complete = "before questioning is complete"

        for skill in [
            "decision-grilling-context-45",
            "domain-grilling-with-docs-context-45",
            "system-definition-interview-context-45",
        ]:
            for relative in [
                f".agents/skills/{skill}/SKILL.md",
                f"Sys4AI/skills/core/{skill}/SKILL.md",
            ]:
                text = _read(relative)
                normalized = " ".join(text.split())
                self.assertIn(prompt, text, relative)
                self.assertIn("/conversation-to-prd", text, relative)
                self.assertIn("/conversation-to-PRD", text, relative)
                self.assertIn("current discussion", text, relative)
                self.assertIn("temp_prd.md", text, relative)
                self.assertIn(no_auto, normalized, relative)
                self.assertIn(before_complete, text, relative)

        policy = _read("Sys4AI/docs/skill_integration_policy.md")
        normalized_policy = " ".join(policy.split())
        self.assertIn(prompt, policy)
        self.assertIn("/conversation-to-PRD", policy)
        self.assertIn("current discussion", policy)
        self.assertIn("temp_prd.md", policy)
        self.assertIn(no_auto, normalized_policy)
        self.assertIn(before_complete, policy)


def _read(relative: str) -> str:
    return (WORKSPACE_ROOT / relative).read_text(encoding="utf-8")


if __name__ == "__main__":
    unittest.main()
